#!/usr/bin/env python

# Copyright (c) 2019, The Personal Robotics Lab, The MuSHR Team, The Contributors of MuSHR
# License: BSD 3-Clause. See LICENSE.md file in root directory.

import rclpy
from mushr_sim.fake_vesc_driver import FakeVescDriver

def main(args=None):
    rclpy.init(args=args)
    rclpy.spin(FakeVescDriver())
    rclpy.shutdown()

    

if __name__ == "__main__":
    main()