#!/usr/bin/env python

# Copyright (c) 2019, The Personal Robotics Lab, The MuSHR Team, The Contributors of MuSHR
# License: BSD 3-Clause. See LICENSE.md file in root directory.

import os
import atexit
import rclpy
from threading import Thread
from mushr_sim.keyboard_teleop import KeyboardTeleop

class TeleopThread(Thread):
    def __init__(self):
        super(TeleopThread, self).__init__()

    def run(self):
        # Temporarily disable keyboard repeats
        os.system("xset r off")
        self.teleop = KeyboardTeleop()
        rclpy.spin(self.teleop)
        self.teleop.root.protocol("WM_DELETE_WINDOW", lambda: rclpy.shutdown())
        self.teleop.root.mainloop()

    def shutdown(self):
        self.teleop.root.quit()
        super(TeleopThread, self).shutdown()

def main(args=None):
    rclpy.init(args=args)
    # Reenable key repeats on exit
    atexit.register(lambda: os.system("xset r on"))

    teleop_thread = TeleopThread()
    teleop_thread.start()
    print("Press Q to quit")
    # rclpy.spin(KeyboardTeleop())
    rclpy.shutdown()
    teleop_thread.teleop.shutdown()

if __name__ == '__main__':
    main()
