#!/usr/bin/env python

# Copyright (c) 2019, The Personal Robotics Lab, The MuSHR Team, The Contributors of MuSHR
# License: BSD 3-Clause. See LICENSE.md file in root directory.

import rclpy
from mushr_sim.mushr_sim import MushrSim

def main(args=None):
    rclpy.init(args=args)
    rclpy.spin(MushrSim())
    rclpy.shutdown()

if __name__ == '__main__':
    main()


